name: sample
description: A FlintDart application
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flint_dart: ^1.0.0+25


dependency_overrides:
  mysql_dart:
    git:
      url: https://github.com/Hybiekay/mysql.dart
      ref: main